### ISSUE TITLE
Reproducing Paper Results

### ISSUE THREAD

**Issue by cdjkim** [jackyin12/MStream#4]
Hi, I am having a hard time reproducing the paper results on all 4 datasets. I ran the uploaded code as it is, but getting greater than 1000 clusters on every single run. 
What would I be doing wrong?

**Comment by daren996** [comment]
Hi Chris, As far as I know, alpha is responsible for discovering new clusters: smaller alpha leads to fewer clusters. I did download the code in this repo and ran it again; for the News dataset, the number of clusters I got was around 300. 
I guess that you considered the greatest label (ID) of the cluster as the number of clusters; whereas a large part of IDs before it is discarded. Although the id can be greater than 1000, the total number of ids is smaller than that.

**Comment by daren996** [comment]
In a word, we won't re-use the IDs discarded.

**Comment by cdjkim** [comment]
Ah, I see how the number of cluster results can be obtained (via only the ClusteringResult.txt files). It is not the K or current_K value in the code, nor the SampleNo1SizeOfEachCluster.txt file. 
I believe I was misled by the naming of the variables and result files.

Appreciate the response Daren :)
